<a href="https://colab.research.google.com/github/rongaladivya/AI_ML_AVANTHI_DIVYA/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
import numpy as np
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get number of elements
a.size

3

In [8]:
# Get size
a=np.array([1,2,3],dtype='int64')
a.itemsize

8

In [21]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
# Get a specific element [r,c]
a[1,5]

13

In [23]:
#Get a specific row
a[:,2]

array([ 3, 10])

In [24]:
a[0,1:-1:2]

array([2, 4, 6])

In [25]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
